# -*- coding: utf-8 -*-
"""Pepcoding.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10Oie5jwyhGqCg9vfoQUu9EFXFGo85n-Y
"""

!pip install autoscraper

from autoscraper import AutoScraper

url = "https://en.wikipedia.org/wiki/N"
wanted_list = ["History","Use in writing systems","Other uses"]

scraper = AutoScraper()
result = scraper.build(url,wanted_list)

print(result)

scraper.get_result_similar('https://en.wikipedia.org/wiki/A')